TMP=/tmp 
TMPD1R=$TMP 
ORACLE_HOSTNAME=centos 
ORACLE_BASE=/u/app/oracle 
ORACLE_HOME=$ORACLE_BASE/product/12.0.1.0/orcIA 
ORACLE_SID=orclA 
ORACLE_TERM=xterm 
ORACLE_UNGNAME=orclA 
PATH=$PATH:$HOME/bin:/usr/bin:/usr/local/bin:$ORACLE_HOME/bin 
LD_LIBRARY_PATH=$ORACLE_HOME/lib:/lib:/usr/lib 
CLASSPATH=$ORACLE_HOME/jdk/jre:$ORACLE_HOME/rdbms/jlib 
TNS_ADMIN=$ORACLE_HOME/network/admin 
#NLS LANG=SPANISH SPAIN.AL32UTF8 
export TMP TMPDIR ORACLE_HOSTNAME ORACLE_BASE ORACLE_HOME ORACLE_SID ORACLE_TERM ORACLE_UNGINAME PATH LD_EIBRARY PATH CLASSPATH TNS_A5MIN 
if [ $SHELL = "/bin/ksh" ] ; then 
   ulimit -p 16384 ulimit -n 65536 
else 
   ulimit -u 16384 -n 65536 fi umask 8221  
